package com.example.fierydragons.controllers;

import javafx.application.Platform;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.scene.control.Button;
import javafx.stage.Stage;

/**
 * The MenuPopupController class manages the menu popup in the game, allowing players to resume or quit.
 * @author: Taken from Jaden's Sprint 2
 */
public class MenuPopupController extends BaseController {

    /**
     * Handles the event when the "Resume" button is clicked.
     * Closes the popup menu, resuming the game.
     *
     * @param event The ActionEvent generated by clicking the "Resume" button.
     */
    @FXML
    private void onResumeButtonClick(ActionEvent event) {
        // This action resumes the game by closing the popup menu.
        ((Stage) (((Button) event.getSource()).getScene().getWindow())).close();
    }

    /**
     * Handles the event when the "Quit" button is clicked.
     * Exits the application completely.
     *
     * @param event The ActionEvent generated by clicking the "Quit" button.
     */
    @FXML
    private void onQuitButtonClick(ActionEvent event) {
        // Exits the application completely.
        Platform.exit();
    }
}
