package com.example.fierydragons.controllers;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Node;
import javafx.scene.Scene;
import javafx.stage.Stage;

import java.io.IOException;

/**
 * The PlayerSelectionController class handles the UI interactions for player selection.
 * @author: Taken from Jaden's Sprint 2
 */
public class PlayerSelectionController extends BaseController {

    /**
     * Triggered when the "Two Players" option is chosen.
     *
     * @param event The ActionEvent generated by selecting the "Two Players" option.
     * @throws IOException If an error occurs while loading the player confirmation screen.
     */
    @FXML
    private void onSelectTwoPlayers(ActionEvent event) throws IOException {
        showPlayerConfirmationScreen(event, 2); // Calls the method to show the confirmation screen for two players.
    }

    /**
     * Triggered when the "Three Players" option is chosen.
     *
     * @param event The ActionEvent generated by selecting the "Three Players" option.
     * @throws IOException If an error occurs while loading the player confirmation screen.
     */
    @FXML
    private void onSelectThreePlayers(ActionEvent event) throws IOException {
        showPlayerConfirmationScreen(event, 3); // Calls the method to show the confirmation screen for three players.
    }

    /**
     * Triggered when the "Four Players" option is chosen.
     *
     * @param event The ActionEvent generated by selecting the "Four Players" option.
     * @throws IOException If an error occurs while loading the player confirmation screen.
     */
    @FXML
    private void onSelectFourPlayers(ActionEvent event) throws IOException {
        showPlayerConfirmationScreen(event, 4); // Calls the method to show the confirmation screen for four players.
    }

    /**
     * Handles the "Back" button click, navigating back to the home screen.
     *
     * @param event The ActionEvent generated by clicking the "Back" button.
     * @throws IOException If an error occurs while switching to the home screen.
     */
    @FXML
    private void onBackButtonClick(ActionEvent event) throws IOException {
        classInstance = getClass(); // Updates classInstance with the current class.
        switcher.switchScene(event, classInstance, "home-view.fxml"); // Uses the switcher to change the scene to the home view.
    }

    /**
     * Displays the player confirmation screen depending on the number of players selected.
     *
     * @param event       The ActionEvent generated by selecting the number of players.
     * @param playerCount The number of players selected.
     * @throws IOException If an error occurs while loading the player confirmation screen.
     */
    @FXML
    private void showPlayerConfirmationScreen(ActionEvent event, int playerCount) throws IOException {
        // Load the FXML for the confirmation screen.
        FXMLLoader loader = new FXMLLoader(getClass().getResource("/com/example/fierydragons/confirm-players-view.fxml"));
        Scene nextScene = new Scene(loader.load()); // Create a new scene with the loaded FXML.

        // Get the current window and set the new scene.
        Stage window = (Stage) ((Node) event.getSource()).getScene().getWindow();
        window.setScene(nextScene);

        // Get the controller for the next scene and initialise it with the selected player count.
        ConfirmPlayerController controller = loader.getController();
        controller.initialiseWithPlayerCount(playerCount);

        window.show(); // Display the window with the new scene.
    }
}
